---
- name: win_file module demo
  hosts: VM0009
  become: yes
  gather_facts: false
  vars:
    myfile: 'C:\Users\Andy.Naiken\Desktop\example.txt'
  tasks:
    - name: Creating an empty file
      ansible.windows.win_file:
        path: "{{ myfile }}"
        state: touch
