---
- hosts: 172.22.2.145
  become: yes
  tasks:
	- name: Join system to AD and add the computer object in the Linux OU
      expect:
        command: /bin/bash -c "/usr/sbin/realm join --user=anpe@cpu.qc.ca"
		responses:
          Password for *: "{{ bind_password }}"